# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(702, 521)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.pushButton_compute = QtWidgets.QPushButton(self.tab)
        self.pushButton_compute.setObjectName("pushButton_compute")
        self.horizontalLayout_12.addWidget(self.pushButton_compute)
        self.pushButton_export = QtWidgets.QPushButton(self.tab)
        self.pushButton_export.setObjectName("pushButton_export")
        self.horizontalLayout_12.addWidget(self.pushButton_export)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_12, 3, 1, 1, 1)
        self.textEdit_input = QtWidgets.QTextEdit(self.tab)
        self.textEdit_input.setObjectName("textEdit_input")
        self.gridLayout_2.addWidget(self.textEdit_input, 1, 1, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_input = QtWidgets.QPushButton(self.tab)
        self.pushButton_input.setObjectName("pushButton_input")
        self.horizontalLayout_13.addWidget(self.pushButton_input)
        self.pushButton_point3D = QtWidgets.QPushButton(self.tab)
        self.pushButton_point3D.setObjectName("pushButton_point3D")
        self.horizontalLayout_13.addWidget(self.pushButton_point3D)
        self.gridLayout_2.addLayout(self.horizontalLayout_13, 2, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_roadName = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_roadName.setObjectName("lineEdit_roadName")
        self.horizontalLayout.addWidget(self.lineEdit_roadName)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.lineEdit_roadID = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_roadID.setObjectName("lineEdit_roadID")
        self.horizontalLayout_11.addWidget(self.lineEdit_roadID)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox_roadType = QtWidgets.QComboBox(self.tab)
        self.comboBox_roadType.setObjectName("comboBox_roadType")
        self.comboBox_roadType.addItem("")
        self.comboBox_roadType.addItem("")
        self.comboBox_roadType.addItem("")
        self.comboBox_roadType.addItem("")
        self.comboBox_roadType.addItem("")
        self.comboBox_roadType.addItem("")
        self.comboBox_roadType.addItem("")
        self.comboBox_roadType.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_roadType)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_currentJunctionId = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_currentJunctionId.setObjectName("lineEdit_currentJunctionId")
        self.horizontalLayout_3.addWidget(self.lineEdit_currentJunctionId)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_speed = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_speed.setObjectName("lineEdit_speed")
        self.horizontalLayout_4.addWidget(self.lineEdit_speed)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.comboBox_predecessorType = QtWidgets.QComboBox(self.tab)
        self.comboBox_predecessorType.setObjectName("comboBox_predecessorType")
        self.comboBox_predecessorType.addItem("")
        self.comboBox_predecessorType.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_predecessorType)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.lineEdit_predecessorId = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_predecessorId.setObjectName("lineEdit_predecessorId")
        self.horizontalLayout_6.addWidget(self.lineEdit_predecessorId)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.comboBox_predecessorContactPoint = QtWidgets.QComboBox(self.tab)
        self.comboBox_predecessorContactPoint.setObjectName("comboBox_predecessorContactPoint")
        self.comboBox_predecessorContactPoint.addItem("")
        self.comboBox_predecessorContactPoint.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_predecessorContactPoint)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.comboBox_successorType = QtWidgets.QComboBox(self.tab)
        self.comboBox_successorType.setObjectName("comboBox_successorType")
        self.comboBox_successorType.addItem("")
        self.comboBox_successorType.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox_successorType)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.lineEdit_successorId = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_successorId.setObjectName("lineEdit_successorId")
        self.horizontalLayout_8.addWidget(self.lineEdit_successorId)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.comboBox_successorContactPoint = QtWidgets.QComboBox(self.tab)
        self.comboBox_successorContactPoint.setObjectName("comboBox_successorContactPoint")
        self.comboBox_successorContactPoint.addItem("")
        self.comboBox_successorContactPoint.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBox_successorContactPoint)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 4, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.listView_allRoads = QtWidgets.QListView(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_allRoads.sizePolicy().hasHeightForWidth())
        self.listView_allRoads.setSizePolicy(sizePolicy)
        self.listView_allRoads.setMaximumSize(QtCore.QSize(100, 10000000))
        self.listView_allRoads.setObjectName("listView_allRoads")
        self.gridLayout.addWidget(self.listView_allRoads, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 702, 19))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OpenDrive Guide"))
        self.pushButton_compute.setText(_translate("MainWindow", "Compute"))
        self.pushButton_export.setText(_translate("MainWindow", "Export"))
        self.pushButton_input.setText(_translate("MainWindow", "Import lane Info"))
        self.pushButton_point3D.setText(_translate("MainWindow", "Import Point Info"))
        self.label.setText(_translate("MainWindow", "Road Name:"))
        self.lineEdit_roadName.setText(_translate("MainWindow", "road"))
        self.label_11.setText(_translate("MainWindow", "Road ID:"))
        self.lineEdit_roadID.setText(_translate("MainWindow", "1"))
        self.label_2.setText(_translate("MainWindow", "Current Road Type :"))
        self.comboBox_roadType.setItemText(0, _translate("MainWindow", "motorway"))
        self.comboBox_roadType.setItemText(1, _translate("MainWindow", "rural"))
        self.comboBox_roadType.setItemText(2, _translate("MainWindow", "town"))
        self.comboBox_roadType.setItemText(3, _translate("MainWindow", "low"))
        self.comboBox_roadType.setItemText(4, _translate("MainWindow", "speed"))
        self.comboBox_roadType.setItemText(5, _translate("MainWindow", "pedestrian"))
        self.comboBox_roadType.setItemText(6, _translate("MainWindow", "bicycle"))
        self.comboBox_roadType.setItemText(7, _translate("MainWindow", "unknown"))
        self.label_3.setText(_translate("MainWindow", "Current Junction ID :"))
        self.lineEdit_currentJunctionId.setText(_translate("MainWindow", "-1"))
        self.label_4.setText(_translate("MainWindow", "Speed Limit :"))
        self.lineEdit_speed.setText(_translate("MainWindow", "50"))
        self.label_5.setText(_translate("MainWindow", "Predecessor Type :"))
        self.comboBox_predecessorType.setItemText(0, _translate("MainWindow", "road"))
        self.comboBox_predecessorType.setItemText(1, _translate("MainWindow", "junction"))
        self.label_6.setText(_translate("MainWindow", "Predecessor ID :"))
        self.lineEdit_predecessorId.setText(_translate("MainWindow", "-1"))
        self.label_7.setText(_translate("MainWindow", "Predecessor Contact Point :"))
        self.comboBox_predecessorContactPoint.setItemText(0, _translate("MainWindow", "start"))
        self.comboBox_predecessorContactPoint.setItemText(1, _translate("MainWindow", "end"))
        self.label_9.setText(_translate("MainWindow", "Successor Type :"))
        self.comboBox_successorType.setItemText(0, _translate("MainWindow", "road"))
        self.comboBox_successorType.setItemText(1, _translate("MainWindow", "junction"))
        self.label_8.setText(_translate("MainWindow", "Successor ID :"))
        self.lineEdit_successorId.setText(_translate("MainWindow", "-1"))
        self.label_10.setText(_translate("MainWindow", "Successor Contact Point :"))
        self.comboBox_successorContactPoint.setCurrentText(_translate("MainWindow", "start"))
        self.comboBox_successorContactPoint.setItemText(0, _translate("MainWindow", "start"))
        self.comboBox_successorContactPoint.setItemText(1, _translate("MainWindow", "end"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Road Info"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Object"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Signalisation"))

